Fix: Input required and not supplied: distribution
Run actions/setup-java@v2
  with:
    java-version: 11
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success

Error: Input required and not supplied: distribution