Fix: Error Input required and not supplied: java-version
Run actions/setup-java@v1
  with:
    java-package: jdk
    architecture: x64
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
Error: Input required and not supplied: java-version